# Generated by Django 6.0.5 on 2026-06-01 08:53

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.TextField(blank=True)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_as_p1', to=settings.AUTH_USER_MODEL)),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_as_p2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مکالمه',
                'verbose_name_plural': 'مکالمه\u200cها',
                'unique_together': {('participant1', 'participant2')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatconversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(choices=[('TEHRAN', 'تهران'), ('QOM', 'قم'), ('SHIRAZ', 'شیراز'), ('ISFAHAN', 'اصفهان'), ('MASHHAD', 'مشهد'), ('SEMNAN', 'سمنان')], default='TEHRAN', max_length=20)),
                ('purpose', models.CharField(choices=[('collaboration', 'همکاری در پروژه'), ('looking_for_team', 'دنبال تیم'), ('looking_for_member', 'دنبال هم\u200cتیمی'), ('learning_partner', 'پارتنر یادگیری'), ('startup', 'همکاری استارتاپی'), ('job_opportunity', 'فرصت شغلی')], default='learning_partner', max_length=20)),
                ('my_skills', models.CharField(choices=[('frontend', 'فرانت\u200cاند'), ('backend', 'بک\u200cاند'), ('fullstack', 'فول\u200cاستک'), ('mobile-development', 'توسعه موبایل'), ('data-science', 'علم داده'), ('artificial-intelligence', 'هوش مصنوعی'), ('cybersecurity', 'امنیت سایبری'), ('devops', 'DevOps'), ('cloud-computing', 'رایانش ابری'), ('ui-ux-design', 'طراحی UI/UX'), ('game-development', 'توسعه بازی'), ('open-source', 'متن\u200cباز')], default='frontend', verbose_name=core.models.Skill)),
                ('skills_needed', models.CharField(choices=[('frontend', 'فرانت\u200cاند'), ('backend', 'بک\u200cاند'), ('fullstack', 'فول\u200cاستک'), ('mobile-development', 'توسعه موبایل'), ('data-science', 'علم داده'), ('artificial-intelligence', 'هوش مصنوعی'), ('cybersecurity', 'امنیت سایبری'), ('devops', 'DevOps'), ('cloud-computing', 'رایانش ابری'), ('ui-ux-design', 'طراحی UI/UX'), ('game-development', 'توسعه بازی'), ('open-source', 'متن\u200cباز')], default='frontend', verbose_name=core.models.Skill)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='درباره خودت بنویس', max_length=500)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatar/')),
                ('github_URL', models.URLField(blank=True, help_text='لینک گیت هاب')),
                ('linkedin_URL', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='profiles', to='core.skill')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
    ]
