# Generated by Django 6.0.5 on 2026-06-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_skills_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
