# Generated by Django 6.0.5 on 2026-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_skills_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, choices=[('frontend', 'فرانت\u200cاند'), ('backend', 'بک\u200cاند'), ('fullstack', 'فول\u200cاستک'), ('mobile-development', 'توسعه موبایل'), ('data-science', 'علم داده'), ('artificial-intelligence', 'هوش مصنوعی'), ('cybersecurity', 'امنیت سایبری'), ('devops', 'DevOps'), ('cloud-computing', 'رایانش ابری'), ('ui-ux-design', 'طراحی UI/UX'), ('game-development', 'توسعه بازی'), ('open-source', 'متن\u200cباز')], related_name='profiles', to='core.skill'),
        ),
    ]
