# Generated by Django 6.0.7 on 2026-08-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='my_skills',
            field=models.CharField(choices=[('frontend', 'فرانت\u200cاند'), ('backend', 'بک\u200cاند'), ('fullstack', 'فول\u200cاستک'), ('mobile-development', 'توسعه موبایل'), ('data-science', 'علم داده'), ('artificial-intelligence', 'هوش مصنوعی'), ('cybersecurity', 'امنیت سایبری'), ('devops', 'DevOps'), ('cloud-computing', 'رایانش ابری'), ('ui-ux-design', 'طراحی UI/UX'), ('game-development', 'توسعه بازی'), ('open-source', 'متن\u200cباز')], default='frontend', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='skills_needed',
            field=models.CharField(choices=[('frontend', 'فرانت\u200cاند'), ('backend', 'بک\u200cاند'), ('fullstack', 'فول\u200cاستک'), ('mobile-development', 'توسعه موبایل'), ('data-science', 'علم داده'), ('artificial-intelligence', 'هوش مصنوعی'), ('cybersecurity', 'امنیت سایبری'), ('devops', 'DevOps'), ('cloud-computing', 'رایانش ابری'), ('ui-ux-design', 'طراحی UI/UX'), ('game-development', 'توسعه بازی'), ('open-source', 'متن\u200cباز')], default='frontend', max_length=50),
        ),
    ]
